require "bundler/gem_tasks"
require "rspec/core/rake_task"
require "rubocop/rake_task"

RSpec::Core::RakeTask.new(:spec)
RuboCop::RakeTask.new

namespace :coverage do
  desc "Collates all result sets generated by the different test runners"
  task :report do
    require "simplecov"

    SimpleCov.collate Dir["coverage/**/.resultset.json"]
    Coveralls::SimpleCov::Formatter.new.format SimpleCov.result
  end
end

task :default => :spec
